### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by FireGamingYT** [FireGamingYT/furbot#8]
When attempting to start bot, it immediately stops again giving this error in console:
I do not know how to fix this error myself.
![image](https://user-images.githubusercontent.com/34064010/81063400-fe131e00-8ed7-11ea-8dfd-bf584a012df2.png)

**Comment by Mc88Donalds** [comment]
looks like discord.py is broken to me
try reinstalling it
btw i also cant start it rn but that is a different error and looks like a problem with discords API

**Comment by FireGamingYT** [comment]
Had 12 packages a while ago, something seems to have removed 7 of the packages including discord.py, installing discord.py did not help as it keeps giving the same error.

**Comment by FireGamingYT** [comment]
Resolved. Had to make a new repl.it and a new github repo.
https://github.com/FireGamingYT/Toothlessbot
